name: hildir-people
version: '${project.version}'
main: com.github.badpop.hildirpeople.HildirPeople
api-version: '1.20'
author: Bad_Pop
description: Le plugin qui permet de gérer les peuples sur Hildir
depend: [ hildir-api ]
commands:
  test:
