name: UltraEconomy
version: 2.8.3
author: Tech
website: UltraEconomy.com
build: 0
main: me.TechsCode.UltraEconomy.base.loader.SpigotLoader
api-version: 1.13
softdepend: [PlaceholderAPI]
loadbefore: [Vault]
load: STARTUP
libraries:
